In [1]:
import pandas as pd
df = pd.read_csv('C:/dataset/be/children-in-need_2025/data/b1_children_in_need_2013_to_2025.csv')

In [2]:
df.head(20)

,time_period,time_identifier,geographic_level,country_code,country_name,region_code,region_name,old_la_code,new_la_code,la_name,category,Anypoint_episodes,Anypoint_child,Started_episodes,Started_child,Ended_episodes,Ended_child,At31_episodes,awaiting_assessment
0,2025,Reporting year,National,E92000001,England,NaN,NaN,NaN,NaN,NaN,Children in Need,756120,704430,396870,371550,353720,334060,402400,16290
1,2025,Reporting year,Regional,E92000001,England,E12000001,North East,NaN,NaN,NaN,Children in Need,44760,41640,21930,20530,20290,19190,24470,720
2,2025,Reporting year,Regional,E92000001,England,E12000002,North West,NaN,NaN,NaN,Children in Need,114190,106870,58080,54570,51740,49240,62450,1470
3,2025,Reporting year,Regional,E92000001,England,E12000003,Yorkshire and The Humber,NaN,NaN,NaN,Children in Need,77690,72110,41390,38870,37380,35460,40310,750
4,2025,Reporting year,Regional,E92000001,England,E12000004,East Midlands,NaN,NaN,NaN,Children in Need,55300,51090,29460,27230,26140,24480,29160,1200
5,2025,Reporting year,Regional,E92000001,England,E12000005,West Midlands,NaN,NaN,NaN,Children in Need,83420,78510,41880,39510,36760,35000,46660,2290
6,2025,Reporting year,Regional,E92000001,England,E12000006,East of England,NaN,NaN,NaN,Children in Need,56900,53710,27640,26260,23660,22580,33230,1200
7,2025,Reporting year,Regional,E92000001,England,E12000007,London,NaN,NaN,NaN,Children in Need,129300,121640,66310,62640,60480,57690,68820,2520
8,2025,Reporting year,Regional,E92000001,England,E12000008,South East,NaN,NaN,NaN,Children in Need,131360,120090,76510,70450,67820,62700,63540,4840
9,2025,Reporting year,Regional,E92000001,England,E12000009,South West,NaN,NaN,NaN,Children in Need,63200,58770,33680,31500,29430,27720,33770,1310
10,2025,Reporting year,Regional,E92000001,England,E13000001,Inner London,NaN,NaN,NaN,Children in Need,48640,45830,24060,22760,21610,20590,27020,910
11,2025,Reporting year,Regional,E92000001,England,E13000002,Outer London,NaN,NaN,NaN,Children in Need,80660,75810,42250,39880,38870,37100,41790,1610
12,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,840.0,E06000047,County Durham,Children in Need,8160,7478,4272,3947,3745,3522,4415,84
13,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,841.0,E06000005,Darlington,Children in Need,1770,1698,723,705,768,748,1002,8
14,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,390.0,E08000037,Gateshead,Children in Need,2617,2444,1116,1059,1045,985,1572,29
15,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,805.0,E06000001,Hartlepool,Children in Need,3010,2674,1642,1488,1669,1508,1341,27
16,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,806.0,E06000002,Middlesbrough,Children in Need,4201,3794,2452,2218,2196,2060,2005,20
17,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,391.0,E08000021,Newcastle upon Tyne,Children in Need,4518,4311,1883,1794,1552,1476,2966,260
18,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,392.0,E08000022,North Tyneside,Children in Need,2483,2369,1036,986,861,829,1622,34
19,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,929.0,E06000057,Northumberland,Children in Need,3960,3739,1872,1791,1830,1750,2130,45

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2132 entries, 0 to 2131
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time_period          2132 non-null   int64
 1   time_identifier      2132 non-null   object
 2   geographic_level     2132 non-null   object
 3   country_code         2132 non-null   object
 4   country_name         2132 non-null   object
 5   region_code          2119 non-null   object
 6   region_name          2119 non-null   object
 7   old_la_code          1976 non-null   float64
 8   new_la_code          1976 non-null   object
 9   la_name              1976 non-null   object
 10  category             2132 non-null   object
 11  Anypoint_episodes    2132 non-null   object
 12  Anypoint_child       2132 non-null   object
 13  Started_episodes     2132 non-null   object
 14  Started_child        2132 non-null   object
 15  Ended_episodes       2132 non-null   object
 16  Ended_child          2132 non-null   object
 17  At31_episodes        2132 non-null   object
 18  awaiting_assessment  2132 non-null   object
dtypes: float64(1), int64(1), object(17)
memory usage: 316.6+ KB

In [7]:
df.describe(include='all')

,time_period,time_identifier,geographic_level,country_code,country_name,region_code,region_name,old_la_code,new_la_code,la_name,category,Anypoint_episodes,Anypoint_child,Started_episodes,Started_child,Ended_episodes,Ended_child,At31_episodes,awaiting_assessment
count,2132.000000,2132,2132,2132,2132,2119,2119,1976.000000,1976,1976,2132,2132,2132,2132,2132,2132,2132,2132,2132
unique,NaN,1,3,1,1,11,11,NaN,161,157,1,1906,1872,1752,1705,1724,1693,1721,587
top,NaN,Reporting year,Local authority,E92000001,England,E12000002,North West,NaN,E06000047,County Durham,Children in Need,x,x,x,x,x,x,1812,c
freq,NaN,2132,1976,2132,2132,314,314,NaN,13,13,2132,5,5,5,5,7,7,6,55
mean,2019.003752,NaN,NaN,NaN,NaN,NaN,NaN,613.972672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,3.746042,NaN,NaN,NaN,NaN,NaN,NaN,278.061077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2013.000000,NaN,NaN,NaN,NaN,NaN,NaN,201.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2016.000000,NaN,NaN,NaN,NaN,NaN,NaN,334.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2019.000000,NaN,NaN,NaN,NaN,NaN,NaN,806.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2022.000000,NaN,NaN,NaN,NaN,NaN,NaN,873.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2025.000000,NaN,NaN,NaN,NaN,NaN,NaN,943.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.isnull().sum()

time_period              0
time_identifier          0
geographic_level         0
country_code             0
country_name             0
region_code             13
region_name             13
old_la_code            156
new_la_code            156
la_name                156
category                 0
Anypoint_episodes        0
Anypoint_child           0
Started_episodes         0
Started_child            0
Ended_episodes           0
Ended_child              0
At31_episodes            0
awaiting_assessment      0
dtype: int64

In [11]:
#Created an explicit “geography level” flag
# region_code / region_name (13 blanks)
# These rows are England/ National total rows

import numpy as np

df["geo_level"] = np.where(
    df["la_name"].notna(), "Local authority",         #Checks if the "la_name" column has a non-null value. If true, assigns "Local authority" to that row.
    np.where(df["region_name"].notna(), "Region", "England")    #This is the nested condition that runs when "la_name" is null. It checks if "region_name" has a non-null value. If true, assigns "Region", otherwise assigns "England".
)

In [13]:
df["region_name"] = df["region_name"].fillna("England") #This replaces any missing values in the "region_name" column with the string "England".
df["region_code"] = df["region_code"].fillna("ENG")  #This replaces any missing values in the "region_code" column with the string "ENG".

df["la_name"] = df["la_name"].fillna("Not applicable") # This replaces any missing values in the "la_name" column with the string "Not applicable".
df["old_la_code"] = df["old_la_code"].fillna("NA")
df["new_la_code"] = df["new_la_code"].fillna("NA")

In [15]:
df.isnull().sum()

time_period            0
time_identifier        0
geographic_level       0
country_code           0
country_name           0
region_code            0
region_name            0
old_la_code            0
new_la_code            0
la_name                0
category               0
Anypoint_episodes      0
Anypoint_child         0
Started_episodes       0
Started_child          0
Ended_episodes         0
Ended_child            0
At31_episodes          0
awaiting_assessment    0
geo_level              0
dtype: int64

In [17]:
df.head(20)

,time_period,time_identifier,geographic_level,country_code,country_name,region_code,region_name,old_la_code,new_la_code,la_name,category,Anypoint_episodes,Anypoint_child,Started_episodes,Started_child,Ended_episodes,Ended_child,At31_episodes,awaiting_assessment,geo_level
0,2025,Reporting year,National,E92000001,England,ENG,England,NA,NA,Not applicable,Children in Need,756120,704430,396870,371550,353720,334060,402400,16290,England
1,2025,Reporting year,Regional,E92000001,England,E12000001,North East,NA,NA,Not applicable,Children in Need,44760,41640,21930,20530,20290,19190,24470,720,Region
2,2025,Reporting year,Regional,E92000001,England,E12000002,North West,NA,NA,Not applicable,Children in Need,114190,106870,58080,54570,51740,49240,62450,1470,Region
3,2025,Reporting year,Regional,E92000001,England,E12000003,Yorkshire and The Humber,NA,NA,Not applicable,Children in Need,77690,72110,41390,38870,37380,35460,40310,750,Region
4,2025,Reporting year,Regional,E92000001,England,E12000004,East Midlands,NA,NA,Not applicable,Children in Need,55300,51090,29460,27230,26140,24480,29160,1200,Region
5,2025,Reporting year,Regional,E92000001,England,E12000005,West Midlands,NA,NA,Not applicable,Children in Need,83420,78510,41880,39510,36760,35000,46660,2290,Region
6,2025,Reporting year,Regional,E92000001,England,E12000006,East of England,NA,NA,Not applicable,Children in Need,56900,53710,27640,26260,23660,22580,33230,1200,Region
7,2025,Reporting year,Regional,E92000001,England,E12000007,London,NA,NA,Not applicable,Children in Need,129300,121640,66310,62640,60480,57690,68820,2520,Region
8,2025,Reporting year,Regional,E92000001,England,E12000008,South East,NA,NA,Not applicable,Children in Need,131360,120090,76510,70450,67820,62700,63540,4840,Region
9,2025,Reporting year,Regional,E92000001,England,E12000009,South West,NA,NA,Not applicable,Children in Need,63200,58770,33680,31500,29430,27720,33770,1310,Region
10,2025,Reporting year,Regional,E92000001,England,E13000001,Inner London,NA,NA,Not applicable,Children in Need,48640,45830,24060,22760,21610,20590,27020,910,Region
11,2025,Reporting year,Regional,E92000001,England,E13000002,Outer London,NA,NA,Not applicable,Children in Need,80660,75810,42250,39880,38870,37100,41790,1610,Region
12,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,840.0,E06000047,County Durham,Children in Need,8160,7478,4272,3947,3745,3522,4415,84,Local authority
13,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,841.0,E06000005,Darlington,Children in Need,1770,1698,723,705,768,748,1002,8,Local authority
14,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,390.0,E08000037,Gateshead,Children in Need,2617,2444,1116,1059,1045,985,1572,29,Local authority
15,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,805.0,E06000001,Hartlepool,Children in Need,3010,2674,1642,1488,1669,1508,1341,27,Local authority
16,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,806.0,E06000002,Middlesbrough,Children in Need,4201,3794,2452,2218,2196,2060,2005,20,Local authority
17,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,391.0,E08000021,Newcastle upon Tyne,Children in Need,4518,4311,1883,1794,1552,1476,2966,260,Local authority
18,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,392.0,E08000022,North Tyneside,Children in Need,2483,2369,1036,986,861,829,1622,34,Local authority
19,2025,Reporting year,Local authority,E92000001,England,E12000001,North East,929.0,E06000057,Northumberland,Children in Need,3960,3739,1872,1791,1830,1750,2130,45,Local authority

In [19]:
df.columns

Index(['time_period', 'time_identifier', 'geographic_level', 'country_code',
       'country_name', 'region_code', 'region_name', 'old_la_code',
       'new_la_code', 'la_name', 'category', 'Anypoint_episodes',
       'Anypoint_child', 'Started_episodes', 'Started_child', 'Ended_episodes',
       'Ended_child', 'At31_episodes', 'awaiting_assessment', 'geo_level'],
      dtype='object')

In [21]:
df.columns = df.columns.str.lower()

In [23]:
df.columns

Index(['time_period', 'time_identifier', 'geographic_level', 'country_code',
       'country_name', 'region_code', 'region_name', 'old_la_code',
       'new_la_code', 'la_name', 'category', 'anypoint_episodes',
       'anypoint_child', 'started_episodes', 'started_child', 'ended_episodes',
       'ended_child', 'at31_episodes', 'awaiting_assessment', 'geo_level'],
      dtype='object')

In [25]:
df = df.drop('time_identifier', axis=1)

In [27]:
df

,time_period,geographic_level,country_code,country_name,region_code,region_name,old_la_code,new_la_code,la_name,category,anypoint_episodes,anypoint_child,started_episodes,started_child,ended_episodes,ended_child,at31_episodes,awaiting_assessment,geo_level
0,2025,National,E92000001,England,ENG,England,NA,NA,Not applicable,Children in Need,756120,704430,396870,371550,353720,334060,402400,16290,England
1,2025,Regional,E92000001,England,E12000001,North East,NA,NA,Not applicable,Children in Need,44760,41640,21930,20530,20290,19190,24470,720,Region
2,2025,Regional,E92000001,England,E12000002,North West,NA,NA,Not applicable,Children in Need,114190,106870,58080,54570,51740,49240,62450,1470,Region
3,2025,Regional,E92000001,England,E12000003,Yorkshire and The Humber,NA,NA,Not applicable,Children in Need,77690,72110,41390,38870,37380,35460,40310,750,Region
4,2025,Regional,E92000001,England,E12000004,East Midlands,NA,NA,Not applicable,Children in Need,55300,51090,29460,27230,26140,24480,29160,1200,Region
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2127,2013,Local authority,E92000001,England,E13000002,Outer London,315.0,E09000024,Merton,Children in Need,2363,2271,1222,1169,877,842,1486,170,Local authority
2128,2013,Local authority,E92000001,England,E13000002,Outer London,317.0,E09000026,Redbridge,Children in Need,4320,4023,2541,2380,2351,2223,1969,29,Local authority
2129,2013,Local authority,E92000001,England,E13000002,Outer London,318.0,E09000027,Richmond upon Thames,Children in Need,1397,1331,617,589,612,601,785,38,Local authority
2130,2013,Local authority,E92000001,England,E13000002,Outer London,319.0,E09000029,Sutton,Children in Need,2550,2392,1294,1169,658,621,1892,99,Local authority
2131,2013,Local authority,E92000001,England,E13000002,Outer London,320.0,E09000031,Waltham Forest,Children in Need,3766,3565,2284,2184,1375,1334,2391,725,Local authority

In [29]:
df = df.drop('country_name', axis=1)

In [31]:
df

,time_period,geographic_level,country_code,region_code,region_name,old_la_code,new_la_code,la_name,category,anypoint_episodes,anypoint_child,started_episodes,started_child,ended_episodes,ended_child,at31_episodes,awaiting_assessment,geo_level
0,2025,National,E92000001,ENG,England,NA,NA,Not applicable,Children in Need,756120,704430,396870,371550,353720,334060,402400,16290,England
1,2025,Regional,E92000001,E12000001,North East,NA,NA,Not applicable,Children in Need,44760,41640,21930,20530,20290,19190,24470,720,Region
2,2025,Regional,E92000001,E12000002,North West,NA,NA,Not applicable,Children in Need,114190,106870,58080,54570,51740,49240,62450,1470,Region
3,2025,Regional,E92000001,E12000003,Yorkshire and The Humber,NA,NA,Not applicable,Children in Need,77690,72110,41390,38870,37380,35460,40310,750,Region
4,2025,Regional,E92000001,E12000004,East Midlands,NA,NA,Not applicable,Children in Need,55300,51090,29460,27230,26140,24480,29160,1200,Region
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2127,2013,Local authority,E92000001,E13000002,Outer London,315.0,E09000024,Merton,Children in Need,2363,2271,1222,1169,877,842,1486,170,Local authority
2128,2013,Local authority,E92000001,E13000002,Outer London,317.0,E09000026,Redbridge,Children in Need,4320,4023,2541,2380,2351,2223,1969,29,Local authority
2129,2013,Local authority,E92000001,E13000002,Outer London,318.0,E09000027,Richmond upon Thames,Children in Need,1397,1331,617,589,612,601,785,38,Local authority
2130,2013,Local authority,E92000001,E13000002,Outer London,319.0,E09000029,Sutton,Children in Need,2550,2392,1294,1169,658,621,1892,99,Local authority
2131,2013,Local authority,E92000001,E13000002,Outer London,320.0,E09000031,Waltham Forest,Children in Need,3766,3565,2284,2184,1375,1334,2391,725,Local authority

In [35]:
# Handling errors
df_raw = df.copy()

In [37]:
# Create numeric analysis columns
import numpy as np
SUPPRESSION_VALUES = ["c", "x", "z", "u"]

In [ ]:
def cin_numeric(series):
    return (
        series
        .replace(SUPPRESSION_VALUES, np.nan)
        .replace("k", 0)
        .astype(float)
    )

In [39]:
def cin_numeric(series):
    return (
        series
        .replace(SUPPRESSION_VALUES, np.nan)
        .replace("k", 0)
        .astype(float)
    )

In [43]:
#This prevents accidental misuse later
cin_columns = [
    "anypoint_child",
    "anypoint_episodes",
    "started_child",
    "started_episodes",
    "ended_child",
    "ended_episodes",
    "at31_episodes",
    "awaiting_assessment"
    
]

for col in cin_columns:
    df[col + "_num"] = cin_numeric(df[col])

In [47]:
df.groupby("time_period")["at31_episodes_num"].sum()

time_period
2013    1191088.0
2014    1251914.0
2015    1241526.0
2016    1251068.0
2017    1235177.0
2018    1286936.0
2019    1269445.0
2020    1236219.0
2021    1231777.0
2022    1280807.0
2023    1279242.0
2024    1259352.0
2025    1276018.0
Name: at31_episodes_num, dtype: float64

In [51]:
# Values suppressed for confidentiality, low reliability, or non-availability 
# were treated as missing and excluded from numeric aggregation, in line with Department for Education guidance. 
# Values marked as ‘k’ (rounding to zero) were treated as zero for aggregation but flagged.

benchmark = df[
    df["at31_episodes_num"].notna() &
    (df["geo_level"] == "Local authority")
]

In [59]:
benchmark

,time_period,geographic_level,country_code,region_code,region_name,old_la_code,new_la_code,la_name,category,anypoint_episodes,...,awaiting_assessment,geo_level,anypoint_child_num,anypoint_episodes_num,started_child_num,started_episodes_num,ended_child_num,ended_episodes_num,at31_episodes_num,awaiting_assessment_num
12,2025,Local authority,E92000001,E12000001,North East,840.0,E06000047,County Durham,Children in Need,8160,...,84,Local authority,7478.0,8160.0,3947.0,4272.0,3522.0,3745.0,4415.0,84.0
13,2025,Local authority,E92000001,E12000001,North East,841.0,E06000005,Darlington,Children in Need,1770,...,8,Local authority,1698.0,1770.0,705.0,723.0,748.0,768.0,1002.0,8.0
14,2025,Local authority,E92000001,E12000001,North East,390.0,E08000037,Gateshead,Children in Need,2617,...,29,Local authority,2444.0,2617.0,1059.0,1116.0,985.0,1045.0,1572.0,29.0
15,2025,Local authority,E92000001,E12000001,North East,805.0,E06000001,Hartlepool,Children in Need,3010,...,27,Local authority,2674.0,3010.0,1488.0,1642.0,1508.0,1669.0,1341.0,27.0
16,2025,Local authority,E92000001,E12000001,North East,806.0,E06000002,Middlesbrough,Children in Need,4201,...,20,Local authority,3794.0,4201.0,2218.0,2452.0,2060.0,2196.0,2005.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2127,2013,Local authority,E92000001,E13000002,Outer London,315.0,E09000024,Merton,Children in Need,2363,...,170,Local authority,2271.0,2363.0,1169.0,1222.0,842.0,877.0,1486.0,170.0
2128,2013,Local authority,E92000001,E13000002,Outer London,317.0,E09000026,Redbridge,Children in Need,4320,...,29,Local authority,4023.0,4320.0,2380.0,2541.0,2223.0,2351.0,1969.0,29.0
2129,2013,Local authority,E92000001,E13000002,Outer London,318.0,E09000027,Richmond upon Thames,Children in Need,1397,...,38,Local authority,1331.0,1397.0,589.0,617.0,601.0,612.0,785.0,38.0
2130,2013,Local authority,E92000001,E13000002,Outer London,319.0,E09000029,Sutton,Children in Need,2550,...,99,Local authority,2392.0,2550.0,1169.0,1294.0,621.0,658.0,1892.0,99.0
2131,2013,Local authority,E92000001,E13000002,Outer London,320.0,E09000031,Waltham Forest,Children in Need,3766,...,725,Local authority,3565.0,3766.0,2184.0,2284.0,1334.0,1375.0,2391.0,725.0

In [61]:
benchmark.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1967 entries, 12 to 2131
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   time_period              1967 non-null   int64
 1   geographic_level         1967 non-null   object
 2   country_code             1967 non-null   object
 3   region_code              1967 non-null   object
 4   region_name              1967 non-null   object
 5   old_la_code              1967 non-null   object
 6   new_la_code              1967 non-null   object
 7   la_name                  1967 non-null   object
 8   category                 1967 non-null   object
 9   anypoint_episodes        1967 non-null   object
 10  anypoint_child           1967 non-null   object
 11  started_episodes         1967 non-null   object
 12  started_child            1967 non-null   object
 13  ended_episodes           1967 non-null   object
 14  ended_child              1967 non-null   object
 15  at31_episodes            1967 non-null   object
 16  awaiting_assessment      1967 non-null   object
 17  geo_level                1967 non-null   object
 18  anypoint_child_num       1966 non-null   float64
 19  anypoint_episodes_num    1966 non-null   float64
 20  started_child_num        1964 non-null   float64
 21  started_episodes_num     1964 non-null   float64
 22  ended_child_num          1963 non-null   float64
 23  ended_episodes_num       1966 non-null   float64
 24  at31_episodes_num        1967 non-null   float64
 25  awaiting_assessment_num  1913 non-null   float64
dtypes: float64(8), int64(1), object(17)
memory usage: 414.9+ KB

In [55]:
df["ended_to_started_ratio"] = (
    df["ended_child_num"] /
    df["started_child_num"]
)

In [57]:
df["ended_to_started_ratio"]

0       0.899098
1       0.934730
2       0.902327
3       0.912272
4       0.899008
          ...
2127    0.720274
2128    0.934034
2129    1.020374
2130    0.531223
2131    0.610806
Name: ended_to_started_ratio, Length: 2132, dtype: float64

In [65]:
from sqlalchemy import create_engine
import urllib

server = "OLUGBEMIGA"      # must match SSMS
database = "Sommerset"
driver = "ODBC Driver 17 for SQL Server"

params = urllib.parse.quote_plus(
    f"DRIVER={{{driver}}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    "Trusted_Connection=yes;"
)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [76]:
df.to_sql("children_in_need", engine, if_exists="replace", index=False, schema="dbo", chunksize=1000)
print("Export complete")

Export complete

In [67]:
benchmark.to_sql("children_in_need", engine, if_exists="replace", index=False, schema="dbo", chunksize=1000)
print("Export complete")

Export complete